apiVersion: v1
kind: Namespace
metadata:
  name: my-app
  labels:
    name: my-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (46dcb9181)
  creationTimestamp: null
  labels:
    io.kompose.service: gin-demo
  name: gin-demo
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gin-demo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.1 (46dcb9181)
      creationTimestamp: null
      labels:
        io.kompose.network/root-default: "true"
        io.kompose.service: gin-demo
    spec:
      containers:
        - image: xiaozuo7/gin-demo:v1
          name: gin-demo
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (46dcb9181)
  creationTimestamp: null
  labels:
    io.kompose.service: gin-demo
  name: gin-demo
  namespace: my-app
spec:
  type: NodePort #手动指定为NodePort类型
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30001 #手动指定nodePort
  selector:
    io.kompose.service: gin-demo
status:
  loadBalancer: { }
