apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.1 (46dcb9181)
  creationTimestamp: null
  labels:
    io.kompose.service: gin-demo
  name: gin-demo
  namespace: default
spec:
  type: NodePort #手动指定为NodePort类型
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30001 #手动指定nodePort
  selector:
    io.kompose.service: gin-demo
status:
  loadBalancer: { }
